In [9]:
import pandas as pd

nav = pd.read_csv("data/raw/02_nav_history.csv")
transactions = pd.read_csv("data/raw/08_investor_transactions.csv")
performance = pd.read_csv("data/raw/07_scheme_performance.csv")

print("NAV COLUMNS")
print(nav.columns.tolist())

print("\nTRANSACTION COLUMNS")
print(transactions.columns.tolist())

print("\nPERFORMANCE COLUMNS")
print(performance.columns.tolist())

NAV COLUMNS
['amfi_code', 'date', 'nav']

TRANSACTION COLUMNS
['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

PERFORMANCE COLUMNS
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

In [11]:
import pandas as pd

nav = pd.read_csv("data/raw/02_nav_history.csv")

print("Shape:", nav.shape)

print("\nMissing Values:")
print(nav.isnull().sum())

print("\nDuplicate Rows:", nav.duplicated().sum())

print("\nNAV <= 0:")
print((nav["nav"] <= 0).sum())

Shape: (46000, 3)

Missing Values:
amfi_code    0
date         0
nav          0
dtype: int64

Duplicate Rows: 0

NAV <= 0:
0

In [13]:
nav["date"] = pd.to_datetime(nav["date"])

nav = nav.sort_values(
    by=["amfi_code", "date"]
)

nav = nav.drop_duplicates()

nav["nav"] = nav.groupby("amfi_code")["nav"].ffill()

nav = nav[nav["nav"] > 0]

print("Cleaned Shape:", nav.shape)

Cleaned Shape: (46000, 3)

In [15]:
print("Missing Values:")
print(nav.isnull().sum())

print("\nDuplicate Rows:")
print(nav.duplicated().sum())

print("\nNAV <= 0:")
print((nav["nav"] <= 0).sum())

Missing Values:
amfi_code    0
date         0
nav          0
dtype: int64

Duplicate Rows:
0

NAV <= 0:
0

In [17]:
print(transactions.head())

  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending

In [19]:
print(transactions["transaction_type"].unique())

['SIP' 'Redemption' 'Lumpsum']

In [21]:
print("Shape:", transactions.shape)

print("\nMissing Values:")
print(transactions.isnull().sum())

print("\nDuplicate Rows:")
print(transactions.duplicated().sum())

print("\nAmount <= 0:")
print((transactions["amount_inr"] <= 0).sum())

print("\nKYC Values:")
print(transactions["kyc_status"].unique())

Shape: (32778, 13)

Missing Values:
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicate Rows:
0

Amount <= 0:
0

KYC Values:
['Verified' 'Pending']

In [23]:
transactions["transaction_date"] = pd.to_datetime(
    transactions["transaction_date"]
)

transactions = transactions.drop_duplicates()

transactions = transactions[
    transactions["amount_inr"] > 0
]

transactions["transaction_type"] = (
    transactions["transaction_type"]
    .str.strip()
    .str.title()
)

valid_kyc = ["Verified", "Pending"]

transactions = transactions[
    transactions["kyc_status"].isin(valid_kyc)
]

print("Cleaned Shape:", transactions.shape)

Cleaned Shape: (32778, 13)

In [25]:
print("Missing Values:")
print(transactions.isnull().sum())

print("\nDuplicate Rows:")
print(transactions.duplicated().sum())

print("\nAmount <= 0:")
print((transactions["amount_inr"] <= 0).sum())

print("\nKYC Values:")
print(transactions["kyc_status"].unique())

Missing Values:
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicate Rows:
0

Amount <= 0:
0

KYC Values:
['Verified' 'Pending']

In [27]:
transactions.to_csv(
    "data/processed/08_investor_transactions_cleaned.csv",
    index=False
)

print("Investor Transactions Saved!")

Investor Transactions Saved!

In [29]:
performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [31]:
performance.dtypes

amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

In [33]:
print("Shape:", performance.shape)

print("\nMissing Values:")
print(performance.isnull().sum())

print("\nDuplicate Rows:")
print(performance.duplicated().sum())

print("\nExpense Ratio < 0.1:")
print((performance["expense_ratio_pct"] < 0.1).sum())

print("\nExpense Ratio > 2.5:")
print((performance["expense_ratio_pct"] > 2.5).sum())

Shape: (40, 19)

Missing Values:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Duplicate Rows:
0

Expense Ratio < 0.1:
0

Expense Ratio > 2.5:
0

In [35]:
performance = performance.drop_duplicates()

performance = performance[
    (performance["expense_ratio_pct"] >= 0.1)
    &
    (performance["expense_ratio_pct"] <= 2.5)
]

performance["risk_grade"] = (
    performance["risk_grade"]
    .astype(str)
    .str.strip()
)

print("Cleaned Shape:", performance.shape)

Cleaned Shape: (40, 19)

In [37]:
print("Duplicate Rows:")
print(performance.duplicated().sum())

print("\nExpense Ratio < 0.1:")
print((performance["expense_ratio_pct"] < 0.1).sum())

print("\nExpense Ratio > 2.5:")
print((performance["expense_ratio_pct"] > 2.5).sum())

Duplicate Rows:
0

Expense Ratio < 0.1:
0

Expense Ratio > 2.5:
0

In [39]:
performance.to_csv(
    "data/processed/07_scheme_performance_cleaned.csv",
    index=False
)

print("Scheme Performance Saved!")

Scheme Performance Saved!

In [41]:
import pandas as pd
import os

os.makedirs("data/processed", exist_ok=True)

files = [
    "01_fund_master.csv",
    "03_aum_by_fund_house.csv",
    "04_monthly_sip_inflows.csv",
    "05_category_inflows.csv",
    "06_industry_folio_count.csv",
    "09_portfolio_holdings.csv",
    "10_benchmark_indices.csv"
]

for file in files:

    df = pd.read_csv(f"data/raw/{file}")

    df = df.drop_duplicates()

    df.to_csv(
        f"data/processed/{file.replace('.csv','_cleaned.csv')}",
        index=False
    )

    print(file, "saved")

01_fund_master.csv saved
03_aum_by_fund_house.csv saved
04_monthly_sip_inflows.csv saved
05_category_inflows.csv saved
06_industry_folio_count.csv saved
09_portfolio_holdings.csv saved
10_benchmark_indices.csv saved

In [43]:
import os

os.makedirs("data/processed", exist_ok=True)

nav.to_csv(
    "data/processed/02_nav_history_cleaned.csv",
    index=False
)

print("02_nav_history_cleaned.csv saved successfully!")

02_nav_history_cleaned.csv saved successfully!

In [45]:
import os

print(os.listdir("data/processed"))

['01_fund_master_cleaned.csv', '02_nav_history_cleaned.csv', '03_aum_by_fund_house_cleaned.csv', '04_monthly_sip_inflows_cleaned.csv', '05_category_inflows_cleaned.csv', '06_industry_folio_count_cleaned.csv', '07_scheme_performance_cleaned.csv', '08_investor_transactions_cleaned.csv', '09_portfolio_holdings_cleaned.csv', '10_benchmark_indices_cleaned.csv']

In [47]:
import sqlite3

conn = sqlite3.connect("bluestock_mf.db")

print("Database Created Successfully!")

Database Created Successfully!

In [49]:
import pandas as pd

fund_master = pd.read_csv("data/processed/01_fund_master_cleaned.csv")

nav = pd.read_csv("data/processed/02_nav_history_cleaned.csv")

transactions = pd.read_csv("data/processed/08_investor_transactions_cleaned.csv")

performance = pd.read_csv("data/processed/07_scheme_performance_cleaned.csv")

aum = pd.read_csv("data/processed/03_aum_by_fund_house_cleaned.csv")

print("All files loaded successfully!")

All files loaded successfully!

In [51]:
print(fund_master.shape)
print(nav.shape)
print(transactions.shape)
print(performance.shape)
print(aum.shape)

(40, 15)
(46000, 3)
(32778, 13)
(40, 19)
(90, 5)

In [53]:
fund_master.to_sql(
    "dim_fund",
    conn,
    if_exists="replace",
    index=False
)

nav.to_sql(
    "fact_nav",
    conn,
    if_exists="replace",
    index=False
)

transactions.to_sql(
    "fact_transactions",
    conn,
    if_exists="replace",
    index=False
)

performance.to_sql(
    "fact_performance",
    conn,
    if_exists="replace",
    index=False
)

aum.to_sql(
    "fact_aum",
    conn,
    if_exists="replace",
    index=False
)

print("All tables loaded successfully!")

All tables loaded successfully!

In [55]:
cursor = conn.cursor()

tables = [
    "dim_fund",
    "fact_nav",
    "fact_transactions",
    "fact_performance",
    "fact_aum"
]

for table in tables:

    count = cursor.execute(
        f"SELECT COUNT(*) FROM {table}"
    ).fetchone()[0]

    print(table, ":", count)

dim_fund : 40
fact_nav : 46000
fact_transactions : 32778
fact_performance : 40
fact_aum : 90

In [57]:
query = """
SELECT scheme_name, aum_crore
FROM fact_performance
ORDER BY aum_crore DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                         scheme_name  aum_crore
0  Mirae Asset Emerging Bluechip Fund - Regular -...      49046
1      Kotak Emerging Equity Fund - Regular - Growth      47469
2     Nippon India Small Cap Fund - Regular - Growth      43630
3         DSP Top 100 Equity Fund - Regular - Growth      41828
4                UTI Mid Cap Fund - Regular - Growth      41728

In [59]:
query = """
SELECT amfi_code,
ROUND(AVG(nav),2) AS avg_nav
FROM fact_nav
GROUP BY amfi_code
ORDER BY avg_nav DESC;
"""

pd.read_sql(query, conn).head()

   amfi_code  avg_nav
0     120844  3705.88
1     125497   797.45
2     100016   566.19
3     149322   439.18
4     101206   435.98

In [61]:
query = """
SELECT state,
COUNT(*) AS total_transactions
FROM fact_transactions
GROUP BY state
ORDER BY total_transactions DESC;
"""

pd.read_sql(query, conn)

             state  total_transactions
0           Punjab                2965
1   Madhya Pradesh                2931
2       Tamil Nadu                2806
3          Gujarat                2780
4      West Bengal                2748
5          Haryana                2736
6        Telangana                2718
7    Uttar Pradesh                2695
8            Delhi                2677
9        Karnataka                2621
10       Rajasthan                2577
11     Maharashtra                2524

In [63]:
query = """
SELECT transaction_type,
COUNT(*) AS total
FROM fact_transactions
GROUP BY transaction_type;
"""

pd.read_sql(query, conn)

  transaction_type  total
0          Lumpsum   8095
1       Redemption   4967
2              Sip  19716

In [65]:
query = """
SELECT scheme_name,
expense_ratio_pct
FROM fact_performance
WHERE expense_ratio_pct < 1;
"""

pd.read_sql(query, conn)

                                          scheme_name  expense_ratio_pct
0            SBI Bluechip Fund - Direct Plan - Growth               0.66
1           SBI Small Cap Fund - Direct Plan - Growth               0.72
2        SBI Magnum Gilt Fund - Regular Plan - Growth               0.77
3            HDFC Top 100 Fund - Direct Plan - Growth               0.92
4   HDFC Mid-Cap Opportunities Fund - Direct - Growth               0.78
5        HDFC Short Term Debt Fund - Regular - Growth               0.56
6           ICICI Pru Bluechip Fund - Direct - Growth               0.80
7            ICICI Pru Liquid Fund - Regular - Growth               0.74
8       Nippon India Large Cap Fund - Direct - Growth               0.72
9                      Nippon India ETF Nifty 50 BeES               0.89
10  Nippon India Gilt Securities Fund - Regular - ...               0.55
11               Kotak Liquid Fund - Regular - Growth               0.60
12               Axis Bluechip Fund - Direct - Growth               0.75
13                ABSL Liquid Fund - Regular - Growth               0.79

In [67]:
query = """
SELECT category,
ROUND(AVG(return_1yr_pct),2) AS avg_return
FROM fact_performance
GROUP BY category;
"""

pd.read_sql(query, conn)

           category  avg_return
0              ELSS       11.16
1         Flexi Cap       16.59
2              Gilt        5.77
3             Index       13.76
4         Index/ETF       10.14
5   Large & Mid Cap       14.91
6         Large Cap       13.72
7            Liquid        6.44
8           Mid Cap       15.98
9    Short Duration        6.83
10        Small Cap       22.26
11            Value       16.67

In [69]:
query = """
SELECT state,
ROUND(SUM(amount_inr),2) AS total_amount
FROM fact_transactions
GROUP BY state
ORDER BY total_amount DESC;
"""

pd.read_sql(query, conn)

             state  total_amount
0           Punjab   315780459.0
1       Tamil Nadu   315177237.0
2   Madhya Pradesh   308312493.0
3        Rajasthan   298645822.0
4          Gujarat   298358940.0
5      West Bengal   297182514.0
6        Telangana   290219284.0
7            Delhi   289633404.0
8    Uttar Pradesh   285368873.0
9          Haryana   279634354.0
10       Karnataka   273753570.0
11     Maharashtra   269513480.0

In [71]:
query = """
SELECT scheme_name,
sharpe_ratio
FROM fact_performance
ORDER BY sharpe_ratio DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                         scheme_name  sharpe_ratio
0           ICICI Pru Liquid Fund - Regular - Growth          7.68
1               Kotak Liquid Fund - Regular - Growth          6.18
2                ABSL Liquid Fund - Regular - Growth          5.14
3       HDFC Short Term Debt Fund - Regular - Growth          1.84
4       SBI Magnum Gilt Fund - Regular Plan - Growth          1.52
5  Nippon India Gilt Securities Fund - Regular - ...          1.33
6          HDFC Top 100 Fund - Regular Plan - Growth          1.06
7      Mirae Asset Large Cap Fund - Regular - Growth          1.06
8          ICICI Pru Bluechip Fund - Direct - Growth          1.03
9     Nippon India Large Cap Fund - Regular - Growth          1.00

In [73]:
query = """
SELECT category,
COUNT(*) AS total_funds
FROM dim_fund
GROUP BY category;
"""

pd.read_sql(query, conn)

  category  total_funds
0     Debt            6
1   Equity           34

In [75]:
query = """
SELECT risk_grade,
COUNT(*) AS total_funds
FROM fact_performance
GROUP BY risk_grade;
"""

pd.read_sql(query, conn)

        risk_grade  total_funds
0             High            8
1              Low            6
2         Moderate           16
3  Moderately High            4
4        Very High            6